//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 02:03:42 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rest.immobilienscout24.de/schema/videoupload/1.0")
package de.is24.rest.api.export.api.impl.video;

