//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 01:34:30 PM MESZ 
//

package de.immobilienscout24.rest.schema.customer._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for customer complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="customer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contractContactDetails" type="{http://rest.immobilienscout24.de/schema/offer/user/1.0}contractContactDetails" minOccurs="0"/>
 *         &lt;element name="professional" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
// @XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Customer")
@XmlRootElement(namespace = "http://rest.immobilienscout24.de/schema/customer/1.0", name = "customer")
@XmlAccessorType(XmlAccessType.NONE)
public class Customer {

	protected boolean professional;

	private String customerNumber;

	/**
	 * Gets the value of the professional property.
	 * 
	 */
	@XmlElement(name = "professional")
	public boolean isProfessional() {
		return professional;
	}

	/**
	 * Sets the value of the professional property.
	 * 
	 */
	public void setProfessional(boolean value) {
		this.professional = value;
	}

	@XmlElement(name = "customerNumber", namespace = "http://rest.immobilienscout24.de/schema/customer/1.0")
	public String getCustomerNumber() {
		return customerNumber;
	}

	public void setCustomerNumber(String customerNumber) {
		this.customerNumber = customerNumber;
	}
}
