//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.31 at 01:34:30 PM MESZ 
//
//@XmlSchema(xmlns = { @XmlNs(prefix = "customer", namespaceURI = "http://rest.immobilienscout24.de/schema/customer/1.0") }, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@javax.xml.bind.annotation.XmlSchema(namespace = "http://rest.immobilienscout24.de/schema/customer/1.0")
package de.immobilienscout24.rest.schema.customer._1;


